#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-03-27
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Verify directories.
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.profile.d
    - ~/.shell.d
  
- name: Profile files.
  copy: src={{ item }} dest=~/
  with_items:
    - .inputrc
    - .profile
    - .profilerc

- name: ShellD files.
  copy: src=.shell.d/ dest=~/.shell.d/

- name: Set execute.
  file: path=.shell.d/lib/greeting mode=0755