#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-04-03
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Set path for bash
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - defaults.yml

- name: Check for bash
  stat:
    path: "{{ path_bash }}"
    get_md5: False
    get_checksum: False
  register: bin_bash

- name: Do bash Actions.
  include: actions.yml
  when: bin_bash.stat.executable is defined and bin_bash.stat.executable
