#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-02
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- hosts: all
  name: Command line items.
  become: False
  roles:
  - bash
  - git
  - inxi
  - misc
  - ssh
  - tmux
  - vim
  - xonsh
  - zsh
