#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-04
# Created:   2017-05-04
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
ssh_keys: |
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}
