#!/bin/sh
# [SublimeLinter shellcheck-exclude:"SC2039" ]
#==============================================================================
#
#         FILE: .shell.d/shellinit
#
#        USAGE: (should be sourced by interactive shell logins)
#
#  DESCRIPTION: Set up working shell environment.
#
# REQUIREMENTS: Bourne-compatible shell
#               uname (via 'coreutils')
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.19.1
#     REVISION: 2018-07-10
#      CREATED: 2016-09-28
#==============================================================================
#------------------------------------------------------------------------------
#-- Notes/known bugs/other issues
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
umask 022

#------------------------------------------------------------------------------
#-- Load settings, functions, symbols, and others
#------------------------------------------------------------------------------
[ -r "${SHELLD}/etc/settings" ]   && . "${SHELLD}/etc/settings"
[ -r "${SHELLD}/lib/functions" ]  && . "${SHELLD}/lib/functions"
[ -r "${SHELLD}/lib/symbols" ]    && . "${SHELLD}/lib/symbols"
[ -r "${SHELLD}/lib/exitcodes" ]  && . "${SHELLD}/lib/exitcodes"
[ -r "${SHELLD}/lib/colors" ]     && . "${SHELLD}/lib/colors"
[ -r "${SHELLD}/lib/aliases" ]    && . "${SHELLD}/lib/aliases"

#------------------------------------------------------------------------------
#-- Load packages
#------------------------------------------------------------------------------
#   Default VCS pacakge
[ "${DEFAULT_VCS}" ] && command -v "${DEFAULT_VCS}" >/dev/null 2>&1 && {
    [ -r "${SHELLD}/packages/${DEFAULT_VCS}" ] && \
       . "${SHELLD}/packages/${DEFAULT_VCS}"
}

command -v docker >/dev/null 2>&1 && {
    [ -r "${SHELLD}/packages/docker" ] && \
       . "${SHELLD}/packages/docker"
}

command -v pcs >/dev/null 2>&1 && {
    [ -r "${SHELLD}/packages/pcs" ] && \
       . "${SHELLD}/packages/pcs"
}

#------------------------------------------------------------------------------
#-- Set up PATH/MANPATH/PERL5LIB/PYTHONPATH
#------------------------------------------------------------------------------
if [ -r "${SHELLD}/etc/paths" ]; then
    while read line
    do
        if [ -d "${line}" ]; then
            pathmunge "${line}" before
        fi
    done <"${SHELLD}/etc/paths"
fi; unset line

if [ -e "${SHELLD}/etc/manpaths" ]; then
    while read line
    do
        if [ -d "${line}" ]; then
            manpathmunge "${line}" before
        fi
    done <"${SHELLD}/etc/manpaths"
fi; unset line

if [ -d "${HOME}/lib/perl5" ]; then
    PERL5LIB="${HOME}/lib/perl5:${PERL5LIB}"
fi

if [ -d "${HOME}/lib/python" ]; then
    PYTHONPATH="${HOME}/lib/python:${PYTHONPATH}"
fi

[ -d "${HOME}/bin" ] && PATH="${HOME}/bin:${PATH}"
[ -d "${HOME}/man" ] && MANPATH="${MANPATH}:${HOME}/man"
[ -d "${HOME}/projects/go" ] && {
    GOPATH="${HOME}/projects/go"
    PATH="${PATH}:${GOPATH}/bin"
}

export PATH MANPATH GOPATH PERL5LIB PYTHONPATH

#------------------------------------------------------------------------------
#-- Set up sysinfo variables and load in platform specific things
#------------------------------------------------------------------------------
command -v uname >/dev/null 2>&1 && {
    read -r -- UNAMES SYSNAME UNAMER PLATFORM <<EOF
    $(uname -nprs)
EOF
    #-- The '-o' option is non-standard, so we'll try it seperately
    UNAMEO=$(uname -o 2>/dev/null)
    [ -z "${HOSTNAME}" ] && HOSTNAME="${SYSNAME}" && export HOSTNAME
    [ -z "${OSTYPE}" ]   && OSTYPE="${UNAMES}"    && export OSTYPE
    export UNAMES UNAMER PLATFORM
    [ -r "${SHELLD}/platform/${UNAMES}" ] && . "${SHELLD}/platform/${UNAMES}"
}
# UNAMER formats for Linux kernels:
# Base Kernel Version <BKV>: K.M.m.c
#       K: Kernel Version
#       M: Kernel Major Revision
#       m: Kernel Minor Revision
#       c: Kernel Corrections -- I haven't seen this in testing thus far
# NOTE: this is not the whole story, but Good Enough(TM) for this
# Some common components:
#       P: Patch Number
#       E: Asynchronous Erratum
#       e: Corrections for Erratum
# el5:   <BKV>-P.<flavour>
# el6/7: <BKV>-P.E.e.<flavour>.<arch>
# fc24:  <BKV>-P.<flavour>.<arch>
# Ubuntu: https://wiki.ubuntu.com/Kernel/FAQ#Kernel.2FFAQ.2FGeneralVersionMeaning.What_does_a_specific_Ubuntu_kernel_version_number_mean.3F
# <BKV>-<ABI number>.<upload number>-<flavour>

#-- This needs to be improved
#   Ubuntu has no equivlent.
unset SYS_RELEASE_FILE
if [ -r /etc/fedora-release ]; then
    SYS_RELEASE_FILE='/etc/fedora-release'
elif [ -r /etc/centos-release ]; then
    SYS_RELEASE_FILE='/etc/centos-release'
elif [ -r /etc/redhat-release ]; then
    # CentOS link-> /etc/centos-release
    # Fedora link-> /etc/fedora-release
    SYS_RELEASE_FILE='/etc/redhat-release'
elif [ -r /etc/solus-release ]; then
    SYS_RELEASE_FILE='/etc/solus-release'
elif [ -r /etc/alpine-release ]; then
    # only has version number
    SYS_RELEASE_FILE='/etc/alpine-release'
elif [ -r /etc/debian_version ]; then
    # only has version number
    SYS_RELEASE_FILE='/etc/debian_version'
elif [ -r /etc/SuSE-release ]; then
    # This file has multiple lines and is deprecated in favor of os-release
    SYS_RELEASE_FILE="$(head -1 /etc/SuSE-release 2>/dev/null)"
elif [ -r /etc/system-release ]; then
    # CentOS link-> /etc/centos-release
    # Fedora link-> /etc/fedora-release
    # RHEL link-> /etc/redhat-release
    SYS_RELEASE_FILE='/etc/system-release'
fi
# This will exist on systems w/lsb-core packages installed and has a very specific format
# [ -r /etc/lsb-release ]    && LSB_RELEASE_FILE='/etc/lsb-release' # Ubuntu/Mint

[ -n "${SYS_RELEASE_FILE}" ] \
    && SYS_RELEASE="$(head -1 "${SYS_RELEASE_FILE}")" \
    && export SYS_RELEASE

#------------------------------------------------------------------------------
#-- (Static) Service Check: Is this a VM/Container?
#   Notes: Small problem w/systemd-detect-virt: it's not 100% reliable...
#          Other commands: virt-what, lspci, facter
#   Reference: https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html
#------------------------------------------------------------------------------
if command -v systemd-detect-virt >/dev/null 2>&1; then
    case "$(systemd-detect-virt --vm)" in
        none )      ;;
        oracle )    PRODUCT_NAME='VirtualBox'               ;;
        vmware )    PRODUCT_NAME='VMWare Virtual Platform'  ;;
        microsoft ) PRODUCT_NAME='MSVirtual Machine'        ;;
        kvm)        PRODUCT_NAME='KVM'                      ;;
        qemu)       PRODUCT_NAME='QEMU'                     ;;
        bochs)      PRODUCT_NAME='Bochs'                    ;;
        * )         PRODUCT_NAME='unknown virtual system'   ;;
    esac
elif [ -r /sys/devices/virtual/dmi/id/product_name ]; then
    PRODUCT_NAME="$(head -1 /sys/devices/virtual/dmi/id/product_name)"
elif [ -f /var/run/vmtoolsd.pid ]; then
    PRODUCT_NAME='VMWare Virtual Platform'
elif [ -f /var/run/vboxadd-service.sh ]; then
    PRODUCT_NAME='VirtualBox'
elif [ -f /proc/version ] && grep -q Microsoft /proc/version; then
    # NOTE: checking /dev/lxss doesn't work as it always errors
    PRODUCT_NAME='Windows Subsystem for Linux'
fi

if [ -n "${PRODUCT_NAME}" ] ; then
    case "${PRODUCT_NAME}" in
        VM[wW]are*   )  HYPERVISOR='VMWare'     ;;
        VirtualBox   )  HYPERVISOR='VirtualBox' ;;
        KVM          )  HYPERVISOR='KVM'        ;;
        HVM*         )  HYPERVISOR='Xen'        ;;
        QEMU         )  HYPERVISOR='QEMU'       ;;
        Bochs        )  HYPERVISOR='Bochs Emu'  ;;
        MSVirtual*   )  HYPERVISOR='Hyper-V'
                        if command -v systemctl >/dev/null 2>&1; then
                            if systemctl -q is-active waagent ; then
                                HYPERVISOR='Azure'
                            fi
                        fi                      ;;
        *[vV]irtual* )  HYPERVISOR='Other'      ;;
        Windows.Sub* )  HYPERVISOR='WinSubsys'  ;;
        *            )                          ;;
    esac
fi
[ -n "${HYPERVISOR}" ] && STAT_VM_CHECK='virtual' && export HYPERVISOR

if [ -f /proc/self/cgroup ] && grep -q '/docker' /proc/self/cgroup ; then
    CONTAINER="Docker"
elif command -v systemd-detect-virt >/dev/null 2>&1; then
    case "$(systemd-detect-virt --container)" in
        none )          ;;
        docker )        CONTAINER="Docker"      ;;
        openvz )        CONTAINER="OpenVZ"      ;;
        lxc-libvirt )   CONTAINER="libvirtLXC"  ;;
        lxc )           CONTAINER="LXC"         ;;
        rkt )           CONTAINER="rkt"         ;;
        * )             CONTAINER='unknown container system'   ;;
    esac
fi
[ -n "${CONTAINER}" ] && STAT_VM_CHECK='container' && export CONTAINER

if [ "${STAT_VM_CHECK}" = 'container' ]; then
    STAT_VM='[C]'
elif [ "${STAT_VM_CHECK}" = 'virtual' ]; then
    STAT_VM='[V]'
elif [ "${UNAMEO}" = 'Msys' ]; then
    STAT_VM='[M]'
elif [ "${UNAMEO}" = 'Cygwin' ]; then
    STAT_VM='[Y]'
elif [ "${UNAMES}" = 'Interix' ]; then
    STAT_VM='[W]'
else
    STAT_VM='---'
fi
export STAT_VM

[ -r "${SHELLD}/location/${HOSTNAME}" ]    && . "${SHELLD}/location/${HOSTNAME}"

#------------------------------------------------------------------------------
#-- Set up editor & pager variables
#------------------------------------------------------------------------------
if command -v nvim >/dev/null 2>&1 ; then
    EDITOR='nvim'
    VISUAL='nvim'
    alias vi='nvim'
elif command -v vim >/dev/null 2>&1 ; then
    EDITOR='vim'
    VISUAL='vim'
    alias vi='vim'
elif command -v vi >/dev/null 2>&1 ; then
    EDITOR='vi'
    VISUAL='vi'
fi

command -v subl >/dev/null 2>&1 && {
    VISUAL='subl'
    EDITOR='subl -w '
}

EDITOR_VERSION=$(${EDITOR} --version 2>/dev/null | head -1)

export EDITOR VISUAL EDITOR_VERSION

if command -v less >/dev/null 2>&1 ; then
    export PAGER='less -FIMRSw -z-2'
    export LESS='-FIMRSw -z-2'
elif command -v more >/dev/null 2>&1 ; then
    export PAGER="more -s"
fi

#------------------------------------------------------------------------------
#-- What command handles priviledge elavation
#------------------------------------------------------------------------------
if [ -z "${CDC_JOINED_DOMAIN}" ]; then
    export PROG_BECOME=sudo
else
    export PROG_BECOME=dzdo
fi

#------------------------------------------------------------------------------
#-- (Static) Service Check: Are we connected remotely?
#------------------------------------------------------------------------------
if [ -n "${SSH_CLIENT}" ]; then
    STAT_SSH='[R]'
elif [ -n "${SSH_CONNECTION}" ]; then
    STAT_SSH='[R]'
elif [ -n "${SSH_TTY}" ]; then
    STAT_SSH='[R]'
else
    STAT_SSH='---'
fi
export STAT_SSH

#------------------------------------------------------------------------------
#-- vte.sh workaround for Tilix (and other VTE-based terminals)
#--     see: https://gnunn1.github.io/tilix-web/manual/vteconfig/
#------------------------------------------------------------------------------
if [ "${TILIX_ID}" ] || [ "${VTE_VERSION}" ]; then
    if [ -r "/etc/profile.d/vte.sh" ]; then
        . "/etc/profile.d/vte.sh"
    elif [ -r "/usr/share/defaults/etc/profile.d/vte.sh" ]; then
        . "/usr/share/defaults/etc/profile.d/vte.sh"
    elif [ -r "/etc/profile.d/vte-2.91.sh" ]; then
        . "/etc/profile.d/vte-2.91.sh"
    fi
fi

#==============================================================================
#------------------------------------------------------------------------------
export ISSET_SHELLINIT=1
#------------------------------------------------------------------------------
#==============================================================================
