#!/bin/sh
# [SublimeLinter shellcheck-exclude:"SC2039" ]
#===============================================================================
#
#         FILE: .shell.d/settings
#
#        USAGE: (should be sourced by shell login)
#
#  DESCRIPTION: Variables which define environment across shells.
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#    OPTIONALS: autojump (via 'autojump')
#               hh (via 'hstr')
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.0.0
#      CREATED: 2016-09-28
#     REVISION: 2016-09-30
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------
umask 022

#----------------------------------------------------------------------
#-- Load functions, symbols, and others
#----------------------------------------------------------------------
[ -r "${SHELLD}/functions/general" ] && . "${SHELLD}/functions/general"
[ -r "${SHELLD}/misc/symbols" ]      && . "${SHELLD}/misc/symbols"
[ -r "${SHELLD}/misc/color" ]        && . "${SHELLD}/misc/color"

#----------------------------------------------------------------------
#-- Static settings
#----------------------------------------------------------------------
export DEFAULT_TIMESTAMP='+%Y%m%d-%H%M%S'   # Prefered datstamp format.
export FIGNORE='~':'.o':'.bak':'.tmp'       # File extensions ignored in name completion
export XDG_CONFIG_HOME="$HOME/.config"      # Set .config directory for XDG
export RSYNC_RSH='ssh'                      # set rsync transport
export HISTSIZE=500                         # In-memory history
export HISTFILESIZE=5000                    # On-disk history
export SAVEHIST="${HISTFILESIZE}"           # Alt On-disk history
if [ "${SHELL}" = zsh ]; then               # zsh has a slightly different format
    export HISTIGNORE='(&|[ ]*|exit|ls|history|[bf]g|reset|clear|cd|cd ..|cd..|fc *)'
else
    export HISTIGNORE='&:[ ]*:exit:ls:history:[bf]g:reset:clear:cd:cd ..:cd..'
fi

#----------------------------------------------------------------------
#-- Optional program settings
#----------------------------------------------------------------------
# Make hh colorful, use keyword search, use blacklist file if it exists
if [ -r "${HOME}/.hh_blacklist" ]; then
    export HH_CONFIG="hicolor,keywords,blacklist"
else
    export HH_CONFIG="hicolor,keywords"
fi
# Set autojump completion for commands
export AUTOJUMP_AUTOCOMPLETE_CMDS='cp vim'

#----------------------------------------------------------------------
#-- VCS Settings
#----------------------------------------------------------------------
# Set this to perfered version control system 
export DEFAULT_VCS='git'
# Set this to false to ignore untracked files, which can speed up repo checks
export VCS_IGNORE_UNTRACKED_FILES='false'
# Set this to false to ignore submodule files, which can speed up repo checks
export VCS_IGNORE_SUBMODULES='true'

#----------------------------------------------------------------------
#-- Set up PATH/MANPATH
#----------------------------------------------------------------------
[ -d "${HOME}/bin" ] && PATH="${HOME}/bin:${PATH}"
[ -d "${HOME}/man" ] && MANPATH="${MANPATH}:${HOME}/man"

if [ -r "${SHELLD}/misc/paths" ]; then
    while read line 
    do
        if [ -d "${line}" ]; then
            pathmunge "${line}" after
        fi
    done <"${SHELLD}/misc/paths"
fi; unset line

if [ -e "${SHELLD}/manpaths" ]; then
    while read line 
    do
        if [ -d "${line}" ]; then
            manpathmunge "${line}" after
        fi
    done <"${SHELLD}/misc/manpaths"
fi; unset line

export PATH MANPATH

#----------------------------------------------------------------------
#-- Set up sysinfo variables
#----------------------------------------------------------------------
# This works great under sh, but not zsh
command -v uname >/dev/null 2>&1 && {
    split "$(uname -nprs)" ' ' UNAMES SYSNAME UNAMER PLATFORM
    [ -z "${HOSTNAME}" ] && HOSTNAME=$SYSNAME && export HOSTNAME
    export UNAMES UNAMER PLATFORM
}

#----------------------------------------------------------------------
#-- Set up editor & pager variables
#----------------------------------------------------------------------
if command -v nvim >/dev/null 2>&1 ; then
    EDITOR='nvim'
    VISUAL='nvim'
    alias vi='nvim'
elif command -v vim >/dev/null 2>&1 ; then
    EDITOR='vim'
    VISUAL='vim'
    alias vi='vim'
elif command -v vi >/dev/null 2>&1 ; then
    EDITOR='vi'
    VISUAL='vi'
fi

command -v sublime_text >/dev/null 2>&1 && {
    VISUAL='sublime_text'
    EDITOR='sublime_text -w '
    alias st='sublime_text'
}

export EDITOR VISUAL

if command -v less >/dev/null 2>&1 ; then
    export PAGER='less -FIMRSw -z-2'
    export LESS='-FIMRSw -z-2'
elif command -v more >/dev/null 2>&1 ; then
    export PAGER="more -s"
fi

#----------------------------------------------------------------------
#-- Dynamic settings
#----------------------------------------------------------------------
