#!/bin/sh
# [SublimeLinter shellcheck-exclude:"SC2039" ]
#===============================================================================
#
#         FILE: .shell.d/shellinit
#
#        USAGE: (should be sourced by interactive shell logins)
#
#  DESCRIPTION: Set up working shell environment.
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#               uname (via 'coreutils')
#    OPTIONALS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.3.0
#      CREATED: 2016-09-28
#     REVISION: 2017-03-09
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------
umask 022

#----------------------------------------------------------------------
#-- Load settings, functions, symbols, and others
#----------------------------------------------------------------------
[ -r "${SHELLD}/etc/settings" ]   && . "${SHELLD}/etc/settings"
[ -r "${SHELLD}/lib/functions" ]  && . "${SHELLD}/lib/functions"
[ -r "${SHELLD}/lib/symbols" ]    && . "${SHELLD}/lib/symbols"
[ -r "${SHELLD}/lib/exitcodes" ]  && . "${SHELLD}/lib/exitcodes"
[ -r "${SHELLD}/lib/colors" ]     && . "${SHELLD}/lib/colors"
[ -r "${SHELLD}/lib/aliases" ]    && . "${SHELLD}/lib/aliases"

#----------------------------------------------------------------------
#-- Load packages
#----------------------------------------------------------------------
#   Default VCS pacakge
[ "${DEFAULT_VCS}" ] && command -v "${DEFAULT_VCS}" >/dev/null 2>&1 && {
    [ -r "${SHELLD}/packages/${DEFAULT_VCS}" ] && \
       . "${SHELLD}/packages/${DEFAULT_VCS}"
    DEFAULT_VCS_VERSION=$(${DEFAULT_VCS} --version 2>/dev/null | head -1)
    export DEFAULT_VCS_VERSION
}

command -v docker >/dev/null 2>&1 && {
    [ -r "${SHELLD}/packages/docker" ] && \
       . "${SHELLD}/packages/docker"
    DOCKER_CLIENT_VERSION=$(docker version --format '{{.Client.Version}} 2>/dev/null')
    DOCKER_SERVER_VERSION=$(docker version --format '{{.Server.Version}} 2>/dev/null')
    export DOCKER_CLIENT_VERSION DOCKER_SERVER_VERSION
}

#----------------------------------------------------------------------
#-- Set up PATH/MANPATH
#----------------------------------------------------------------------
[ -d "${HOME}/bin" ] && PATH="${HOME}/bin:${PATH}"
[ -d "${HOME}/man" ] && MANPATH="${MANPATH}:${HOME}/man"

if [ -r "${SHELLD}/etc/paths" ]; then
    while read line
    do
        if [ -d "${line}" ]; then
            pathmunge "${line}" after
        fi
    done <"${SHELLD}/etc/paths"
fi; unset line

if [ -e "${SHELLD}/etc/manpaths" ]; then
    while read line
    do
        if [ -d "${line}" ]; then
            manpathmunge "${line}" after
        fi
    done <"${SHELLD}/etc/manpaths"
fi; unset line

export PATH MANPATH

#----------------------------------------------------------------------
#-- Set up sysinfo variables and load in platform specific things
#----------------------------------------------------------------------
command -v uname >/dev/null 2>&1 && {
    read -r -- UNAMES SYSNAME UNAMER PLATFORM <<EOF
    $(uname -nprs)
EOF
    [ -z "${HOSTNAME}" ] && HOSTNAME="${SYSNAME}" && export HOSTNAME
    [ -z "${OSTYPE}" ]   && OSTYPE="${UNAMES}"    && export OSTYPE
    export UNAMES UNAMER PLATFORM
    [ -r "${SHELLD}/platform/${UNAMES}" ] && . "${SHELLD}/platform/${UNAMES}"
}

[ -r "${SHELLD}/location/${HOSTNAME}" ]    && . "${SHELLD}/location/${HOSTNAME}"

#----------------------------------------------------------------------
#-- Set up editor & pager variables
#----------------------------------------------------------------------
if command -v nvim >/dev/null 2>&1 ; then
    EDITOR='nvim'
    VISUAL='nvim'
    alias vi='nvim'
elif command -v vim >/dev/null 2>&1 ; then
    EDITOR='vim'
    VISUAL='vim'
    alias vi='vim'
elif command -v vi >/dev/null 2>&1 ; then
    EDITOR='vi'
    VISUAL='vi'
fi

command -v sublime_text >/dev/null 2>&1 && {
    VISUAL='sublime_text'
    EDITOR='sublime_text -w '
    alias st='sublime_text'
}

EDITOR_VERSION=$(${EDITOR} --version 2>/dev/null | head -1)

export EDITOR VISUAL EDITOR_VERSION

if command -v less >/dev/null 2>&1 ; then
    export PAGER='less -FIMRSw -z-2'
    export LESS='-FIMRSw -z-2'
elif command -v more >/dev/null 2>&1 ; then
    export PAGER="more -s"
fi

#----------------------------------------------------------------------
#-- What command handles priviledge elavation
#----------------------------------------------------------------------
if command -v dzdo      >/dev/null 2>&1 ; then
    export PROG_BECOME=dzdo
elif command -v sudo    >/dev/null 2>&1 ; then
    export PROG_BECOME=sudo
fi
#===============================================================================
#----------------------------------------------------------------------
export ISSET_SHELLINIT=1
#----------------------------------------------------------------------
#===============================================================================
