#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-04-03
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Check for /usr/bin/zsh
  stat:
    path: /usr/bin/zsh
    get_md5: False
    get_checksum: False
  register: bin_zsh

- name: Do zsh Actions.
  include: actions.yml
  when: bin_zsh.stat.executable is defined and bin_zsh.stat.executable
