#!/bin/sh
#===============================================================================
#
#         FILE: .shell.d/misc/greeting
#
#        USAGE: (should be run by shell login)
#
#  DESCRIPTION: Displays some useful/fun info upon login
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#               ncurses (tput, tset, infocmp)
#    OPTIONALS: ddate
#               fortune
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.0.0
#      CREATED: 2016-10-04
#     REVISION: 2016-10-04
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#-- Display some useful information
#----------------------------------------------------------------------
echo -e "${c_white}You're logged into ${c_bold}$HOSTNAME${c_norm}${c_white} in a(n) ${c_bold}$TERM${c_norm}${c_white} terminal with:${c_norm}
    ${c_white}${c_bold}System:${c_norm} ${c_purple}${UNAMES} (${UNAMER})${c_norm}
    ${c_white}${c_bold}Shell:${c_norm}  ${c_purple}${SHELLSTRING}${c_norm}
    ${c_white}${c_bold}Pager:${c_norm}  ${c_purple}${PAGER}${c_norm}
    ${c_white}${c_bold}Editor:${c_norm} ${c_purple}${EDITOR}${c_norm}
    ${c_white}${c_bold}VCS:${c_norm}    ${c_purple}${DEFAULT_VCS}${c_norm}"

# Print the Discordian date.
if [ -x $(which ddate 2>/dev/null) ]; then
    echo -e "${c_cyan}$(ddate +'Today is %{%A, the %e of %B%}, %Y YOLD. %N%nCelebrate %H')${c_norm}"
fi

# Print a random, hopefully interesting, adage.
if [ -x $(which fortune 2>/dev/null) ]; then
    echo -e "${c_purple}$(fortune -s)${c_norm}"
fi

