#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-04
# Created:   2017-05-04
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
# I am aware of the multi package trick outlined here:
#   https://ansible-tips-and-tricks.readthedocs.io/en/latest/os-dependent-tasks/installing_packages/
# however am currently not using that to retain more fine-grained control, and
# due to what appears to be a major bug in DNF keeping 'become' from working

- name: Tmux Install Packages (APK)
  apk:
    name: tmux
    state: present
  when: ansible_pkg_mgr == "apk"

- name: Tmux Install Packages (APT)
  apt:
    name: tmux
    state: present
  when: ansible_pkg_mgr == "apt"

# The DNF module appears to have a bug not allowing 'become' to work
# - name: Tmux Install Packages (DNF)
#   dnf:
#     name: tmux
#     state: present
#   when: ansible_pkg_mgr == "dnf"

- name: Tmux Install Packages (YUM)
  yum:
    name: tmux
    state: present
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

