#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-04-03
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Check for /usr/bin/xonsh
  stat:
    path: /usr/bin/xonsh
    get_md5: False
    get_checksum: False
  register: bin_xonsh

- name: Do xonsh Actions.
  include: actions.yml
  when: bin_xonsh.stat.executable is defined and bin_xonsh.stat.executable

