#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-03-27
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Verify directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - ~/.config
    - ~/.config/xonsh
    - ~/.local
    - ~/.local/share
    - ~/.local/share/xonsh
  
- name: Xonsh files.
  copy:
    src: "{{ item }}"
    dest: ~/
  with_items:
    - .xonshrc

- name: Xonsh config files.
  copy:
    src: .config/xonsh/
    dest: ~/.config/xonsh/

- name: Xonsh local files.
  copy:
    src: .local/share/xonsh/
    dest: ~/.local/share/xonsh/

