#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-02
# Created:   2017-03-23
# Copyright: 2017, awmyhr
# License:   Apache-2.0
# Based on:  https://gist.github.com/hongqn/62d528116eb5a4a9e4b7
#===============================================================================
---
- name: Ensure ssh public key.
  authorized_key:
    user: "{{ ansible_user }}"
    key: |
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/bespin_id_ed25519.pub') }}
         {{ lookup('file', lookup('env', 'HOME') + '/.ssh/bespin_id_rsa.pub') }}
    state: present
    exclusive: True
    manage_dir: yes

- name: Common Directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - ~/bin
    - ~/etc
    - ~/lib
    - ~/man
    - ~/projects
    - ~/share
    - ~/store
    - ~/tmp
    - ~/var
    - ~/var/log
    - ~/work
