#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-02
# Created:   2017-05-02
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
ssh_ControlPath: 'ControlPath ~/tmp/.ssh_mux-%r_%h_%p'
ssh_ControlPersist: 'ControlPersist 60'
ssh_HostKeyAlgorithms: 'HostKeyAlgorithms ssh-rsa-cert-v01@openssh.com,ssh-rsa'
ssh_Ciphers: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
ssh_KexAlgorithms: 'KexAlgorithms diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1'
ssh_MACs: 'MACs hmac-sha2-512,hmac-sha2-256,hmac-ripemd160'
