#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-03-27
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
# Based on:  https://github.com/sloria/dotfiles/blob/master/roles/vim/tasks/main.yml
#===============================================================================
---
- name: Verify directories.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - ~/.vim
    - ~/.vim/autoload
  
- name: Vim files.
  copy:
    src: .vim/
    dest: ~/.vim/
  register: vimrc

- name: Get vim-plug.
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
  ignore_errors: yes
  register: vimplug

# This requires terminal I/O, need a silent way...
# - name: Install vim-plug.
#   command: vim +PlugInstall +qall
#   ignore_errors: yes
#   when: vimrc.changed or vimplug.changed