#!/bin/sh
# [SublimeLinter shellcheck-exclude:"SC2039" ]
#===============================================================================
#
#         FILE: .shell.d/etc/settings
#
#        USAGE: (should be sourced by .shell.d/shellinit)
#
#  DESCRIPTION: Variables which define environment across shells. This file is
#                   primarily for static configuration.
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#    OPTIONALS: autojump (via 'autojump')
#               hh (via 'hstr')
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.0.0
#      CREATED: 2016-09-28
#     REVISION: 2016-10-04
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#-- Static settings
#----------------------------------------------------------------------
export DEFAULT_TIMESTAMP='+%Y%m%d-%H%M%S'   # Prefered datstamp format.
export FIGNORE='~':'.o':'.bak':'.tmp'       # File extensions ignored in name completion
export XDG_CONFIG_HOME="$HOME/.config"      # Set .config directory for XDG
export RSYNC_RSH='ssh'                      # set rsync transport
export HISTSIZE=500                         # In-memory history
export HISTFILESIZE=5000                    # On-disk history
export SAVEHIST="${HISTFILESIZE}"           # Alt On-disk history
if [ "${SHELL}" = zsh ]; then               # zsh has a slightly different format
    export HISTIGNORE='(&|[ ]*|exit|ls|history|[bf]g|reset|clear|cd|cd ..|cd..|fc *)'
else
    export HISTIGNORE='&:[ ]*:exit:ls:history:[bf]g:reset:clear:cd:cd ..:cd..'
fi

#----------------------------------------------------------------------
#-- Optional program settings
#----------------------------------------------------------------------
# Make hh colorful, use keyword search, use blacklist file if it exists
if [ -r "${HOME}/.hh_blacklist" ]; then
    export HH_CONFIG="hicolor,keywords,blacklist"
else
    export HH_CONFIG="hicolor,keywords"
fi
# Set autojump completion for commands
export AUTOJUMP_AUTOCOMPLETE_CMDS='cp vim'

#----------------------------------------------------------------------
#-- VCS Settings
#----------------------------------------------------------------------
# Set this to perfered version control system 
export DEFAULT_VCS='git'
# Set this to false to ignore untracked files, which can speed up repo checks
export VCS_IGNORE_UNTRACKED_FILES='false'
# Set this to false to ignore submodule files, which can speed up repo checks
export VCS_IGNORE_SUBMODULES='true'
