#!/bin/sh
#===============================================================================
#
#         FILE: tools/install_SublimeText
#
#        USAGE: (should be run by shell bootstrap)
#
#  DESCRIPTION: Install Sublime Text. This is originally based on the gist:
#                   https://gist.github.com/dkd903/8ba3f51313c1781cc571
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#    OPTIONALS: curl (via 'curl')
#               root access for system-level install
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.0.0-alpha
#      CREATED: 2016-09-28
#     REVISION: 2016-10-11
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------

if [ "$(id -u)" = 0 ]; then
    TARGET='/opt'
    DTFILE='/usr/share/applications/sublime-text-3.desktop'
    SYMLINK='/usr/local/bin/sublime_text'
else
    TARGET="${HOME}/Applications"
    mkdir -p "${HOME}/Applications"
    DTFILE="${HOME}/.local/share/applications/sublime-text-3.desktop"
    SYMLINK="${HOME}/bin/sublime_text"
fi

DOWNLOAD='https://download.sublimetext.com/sublime_text_3_build_3126_x64.tar.bz2'
TARBALL='/tmp/sublime-text-3.tar.bz2'

SHORTCUT="
[Desktop Entry]
Version=1.0
Type=Application
Name=Sublime Text
GenericName=Text Editor
Comment=Sophisticated text editor for code, markup and prose
Exec=${TARGET}/sublime_text_3/sublime_text %F
Terminal=false
MimeType=text/plain;
# Icon=${TARGET}/sublime_text_3/Icon/128x128/sublime-text.png
Icon=sublime-text
# Icon=sublime-text-3
Categories=Utilities;Programming;
StartupNotify=true
Actions=Window;Document;
Encoding=UTF-8

[Desktop Action Window]
Name=New Window
Exec=${TARGET}/sublime_text/sublime_text -n
OnlyShowIn=Unity;

[Desktop Action Document]
Name=New File
Exec=${TARGET}/sublime_text/sublime_text --command new_file
OnlyShowIn=Unity;
"
curl -L "${DOWNLOAD}" -o "${TARBALL}" || exit "${?}"

cd "${TARGET}"
tar -xjf "${TARBALL}"
ln -s "${TARGET}/sublime_text_3/sublme_text" "${SYMLINK}"

printf "%s\n" "${SHORTCUT}" > "${DTFILE}"

printf "%s\n" "Successfully installed SublimeText to ${TARGET}/sublime_text_3:"

"${TARGET}/sublime_text_3/sublime_text" --version
