#!/bin/sh
# [SublimeLinter shellcheck-exclude:"SC2039" ]
#===============================================================================
#
#         FILE: .shell.d/etc/settings
#
#        USAGE: (should be sourced by .shell.d/shellinit)
#
#  DESCRIPTION: Variables which define environment across shells. This file is
#                   primarily for static configuration.
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#    OPTIONALS: autojump (via 'autojump')
#               hh (via 'hstr')
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.3.0
#      CREATED: 2016-10-31
#     REVISION: 2017-04-04
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#-- Misc static settings
#----------------------------------------------------------------------
export DEFAULT_TIMESTAMP='+%Y%m%d-%H%M%S'   # Prefered datstamp format.
export FIGNORE='~':'.o':'.bak':'.tmp'       # File extensions ignored in name completion
export XDG_CONFIG_HOME="$HOME/.config"      # Set .config directory for XDG
export RSYNC_RSH='ssh'                      # set rsync transport
export HISTSIZE=500                         # In-memory history
export HISTFILESIZE=5000                    # On-disk history
export SAVEHIST="${HISTFILESIZE}"           # Alt On-disk history
export S_TIME_FORMAT='ISO'                  # ISO timestamps for sysutils
if [ "${ZSH_NAME}" = zsh ]; then            # zsh has a slightly different format
    export HISTIGNORE='(&|[ ]*|exit|ls|history|[bf]g|reset|clear|cd|cd ..|cd..|fc *)'
    # format for time, ex:
    # ls -latr U: 0.002 S: 0.003 (T: 0.005) C: 89% M: 0
    export TIMEFMT="--- Time for: ${c_blue}%J${c_norm} ---
U: %*U S: %*S (T: %*E) C: %P | M: (%K) %M W: %W | I/O: %I/%O"
else
    export HISTIGNORE='&:[ ]*:exit:ls:history:[bf]g:reset:clear:cd:cd ..:cd..'
    export TIMEFORMAT='U: %lU S: %lS (T: %lE) C: %P'
fi

#----------------------------------------------------------------------
#-- Optional program settings
#----------------------------------------------------------------------
# Make hh colorful, use keyword search, use blacklist file if it exists
if [ -r "${HOME}/.hh_blacklist" ]; then
    export HH_CONFIG="hicolor,keywords,blacklist"
else
    export HH_CONFIG="hicolor,keywords"
fi

export AUTOJUMP_AUTOCOMPLETE_CMDS='cp vim'  # Set autojump completion for commands

#----------------------------------------------------------------------
#-- VCS Settings
#----------------------------------------------------------------------
# Set this to perfered version control system
export DEFAULT_VCS='git'
# Set this to false to ignore untracked files, which can speed up repo checks
export VCS_IGNORE_UNTRACKED_FILES='false'
# Set this to false to ignore submodule files, which can speed up repo checks
export VCS_IGNORE_SUBMODULES='true'
# Set this to true for a detailed vcs status line, otherwise just clean/dirty
export VCS_DETAILED_STATUS='true'
