#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-10
# Created:   2017-05-09
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Screenfetch Download.
  git:
    repo: "https://github.com/KittyKatt/screenFetch.git"
    dest: "{{ role_path }}/cache/screenFetch"
  ignore_errors: yes
  delegate_to: localhost
  run_once: True

- name: Screenfetch Script.
  copy:
    src: "{{ role_path }}/cache/screenFetch/screenfetch-dev"
    dest: ~/bin/screenfetch
    mode: 0755

- name: Screenfetch Man Page.
  copy:
    src: "{{ role_path }}/cache/screenFetch/screenfetch.1"
    dest: ~/man/man1/screenfetch.1
    mode: 0644

