#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-09
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Misc dotfiles.
  copy:
    src: "{{ item }}"
    dest: ~/
  with_items:
    - .csslintrc
    - .editorconfig

- name: Misc config files.
  copy:
    src: .config/
    dest: ~/.config/

- name: Ack.
  include: install-ack.yml
  tags: ack

- name: Screenfetch.
  include: install-screenfetch.yml
  tags: screenfetch
