#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-04
# Created:   2017-03-27
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
- name: Misc dotfiles.
  copy:
    src: "{{ item }}"
    dest: ~/
  with_items:
    - .csslintrc
    - .editorconfig

- name: Misc config files.
  copy:
    src: .config/
    dest: ~/.config/

- name: Ack Download.
  get_url:
    url: https://github.com/petdance/ack2/blob/master/ack
    dest: "{{ role_path }}/cache/ack"
  ignore_errors: yes
  delegate_to: localhost
  tags: ack

- name: Ack Install.
  file:
    src: "{{ role_path }}/cache/ack"
    dest: ~/bin/ack
    state: file
    mode: 0755
  ignore_errors: yes
  tags: ack
