#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   20180227-111906
# Created:   2017-05-09
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
#-- Building ack is too much of a PIA for this project, so just download the file
#   However, in some (corportate) environments, we need to specify the cipher,
#   which cannot be done with Ansible's get_url, thus fall back to running
#   curl manually like an animal...
- name: Ack Download.
  command: curl -L --ciphers TLSv1 "https://beyondgrep.com/ack-2.22-single-file" -o "{{ role_path }}/cache/ack"
  ignore_errors: yes
  delegate_to: localhost
  run_once: True

- name: Ack Script.
  copy:
    src: "{{ role_path }}/cache/ack"
    dest: ~/bin/ack
    mode: 0755


