#!/bin/sh
#===============================================================================
#
#         FILE: .shell.d/platform/Linux
#
#        USAGE: (should be sourced by .shell.d/shellinit)
#
#  DESCRIPTION: Linux specific settings/functions/etc
#
#      OPTIONS: ---
# REQUIREMENTS: Bourne-compatible shell
#               'uname -s' reports 'Linux'
#    OPTIONALS: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: awmyhr, awmyhr@gmail.com
#      VERSION: 1.1.0
#     REVISION: 2018-07-13
#      CREATED: 2016-10-10
#===============================================================================
#----------------------------------------------------------------------
#-- Notes/known bugs/other issues
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#-- Platform ENV vars
#----------------------------------------------------------------------

#----------------------------------------------------------------------
#-- Alias overrides
#----------------------------------------------------------------------
alias mkdir='mkdir -pv'

alias psmem='ps --sort="-vsz"  -eo "user,pid,ppid,vsz,args"  | head '
alias pscpu='ps --sort="-%cpu" -eo "user,pid,ppid,%cpu,args" | head '
