#===============================================================================
# Project:   awmyhr DotFiles (Public)
# Author:    Myhr, Andy
# Revised:   2017-05-11
# Created:   2017-05-11
# Copyright: 2017, awmyhr
# License:   Apache-2.0
#===============================================================================
---
dependencies:
  - {role: common }
